name: Cache Demo
on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: prime-cache-e2c0f27
      uses: actions/cache@v4
      with:
        key: cache-e2c0f27
        path: ~/.npm
        
    - name: Demo install (uses cache)
      run: npm ci  # Works NOW with package-lock.json
